spring.application.name=suspension-backend

server.port=8080

# ============================================================
# MYSQL
# ============================================================

spring.datasource.url=jdbc:mysql://localhost:3306/suspension_db?useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=Ashu@1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================================
# JPA
# ============================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# MQTT
# ============================================================

mqtt.broker=tcp://localhost:1883
mqtt.topic=vehicle/suspension/telemetry
mqtt.client-id=suspension-backend